webtalk_init -webtalk_dir D:\\sources\\daisyplus_openssd_toshiba_19.1_20211217_lpddr4\\cosm-plus-sys.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-12-20 16:56:51" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "sbc8vu81gbj3bfvpl947th54qj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_43" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "43" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.058 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1639982553556" -context "sdk\\\\bsp/1639982553556"
webtalk_add_data -client sdk -key hwid -value "1639969156772" -context "sdk\\\\bsp/1639982553556"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1639982553556"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1639982553556"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1639982553556"
webtalk_add_data -client sdk -key uid -value "1639982559941" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key hwid -value "1639969156772" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key bspid -value "1639982553556" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key projSize -value "702.71875" -context "sdk\\\\application/1639982559941"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key DebugCount -value "7" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1639987011081"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1639987011081"
webtalk_transmit -clientid 3432424307 -regid "" -xml D:\\sources\\daisyplus_openssd_toshiba_19.1_20211217_lpddr4\\cosm-plus-sys.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\sources\\daisyplus_openssd_toshiba_19.1_20211217_lpddr4\\cosm-plus-sys.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\sources\\daisyplus_openssd_toshiba_19.1_20211217_lpddr4\\cosm-plus-sys.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
