domain_path: D:\tmp\daisyplus_micron_new_lpddr4_b_260225_2\ws\daisyplus\export\daisyplus\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
