#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ 1000000000


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 1000000000


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ZYNQ
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 8U

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_DEVICE_ID 0U
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_0_ECC 0U
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0x45000000U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0x45003FFFU
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_AXI_BRAM_CTRL_1_DEVICE_ID 1U
#define XPAR_AXI_BRAM_CTRL_1_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_1_ECC 0U
#define XPAR_AXI_BRAM_CTRL_1_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_1_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_1_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_1_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_BASEADDR 0x45100000U
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_HIGHADDR 0x45103FFFU
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_2 */
#define XPAR_AXI_BRAM_CTRL_2_DEVICE_ID 2U
#define XPAR_AXI_BRAM_CTRL_2_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_2_ECC 0U
#define XPAR_AXI_BRAM_CTRL_2_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_2_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_2_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_2_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_2_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_2_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_2_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_2_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_BASEADDR 0x45200000U
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_HIGHADDR 0x45203FFFU
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_3 */
#define XPAR_AXI_BRAM_CTRL_3_DEVICE_ID 3U
#define XPAR_AXI_BRAM_CTRL_3_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_3_ECC 0U
#define XPAR_AXI_BRAM_CTRL_3_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_3_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_3_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_3_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_3_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_3_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_3_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_3_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_BASEADDR 0x45300000U
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_HIGHADDR 0x45303FFFU
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_4 */
#define XPAR_AXI_BRAM_CTRL_4_DEVICE_ID 4U
#define XPAR_AXI_BRAM_CTRL_4_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_4_ECC 0U
#define XPAR_AXI_BRAM_CTRL_4_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_4_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_4_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_4_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_4_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_4_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_4_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_4_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_BASEADDR 0x45400000U
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_HIGHADDR 0x45403FFFU
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_5 */
#define XPAR_AXI_BRAM_CTRL_5_DEVICE_ID 5U
#define XPAR_AXI_BRAM_CTRL_5_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_5_ECC 0U
#define XPAR_AXI_BRAM_CTRL_5_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_5_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_5_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_5_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_5_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_5_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_5_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_5_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_BASEADDR 0x45500000U
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_HIGHADDR 0x45503FFFU
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_6 */
#define XPAR_AXI_BRAM_CTRL_6_DEVICE_ID 6U
#define XPAR_AXI_BRAM_CTRL_6_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_6_ECC 0U
#define XPAR_AXI_BRAM_CTRL_6_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_6_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_6_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_6_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_6_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_6_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_6_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_6_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_BASEADDR 0x45600000U
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_HIGHADDR 0x45603FFFU
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_7 */
#define XPAR_AXI_BRAM_CTRL_7_DEVICE_ID 7U
#define XPAR_AXI_BRAM_CTRL_7_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_7_ECC 0U
#define XPAR_AXI_BRAM_CTRL_7_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_7_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_7_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_7_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_7_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_7_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_7_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_7_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_BASEADDR 0x45700000U
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_HIGHADDR 0x45703FFFU
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_0_WRITE_ACCESS 0U
#define XPAR_BRAM_0_BASEADDR 0x45000000U
#define XPAR_BRAM_0_HIGHADDR 0x45003FFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_BRAM_1_DEVICE_ID XPAR_AXI_BRAM_CTRL_1_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_1_WRITE_ACCESS 0U
#define XPAR_BRAM_1_BASEADDR 0x45100000U
#define XPAR_BRAM_1_HIGHADDR 0x45103FFFU
#define XPAR_BRAM_1_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_1_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_2 */
#define XPAR_BRAM_2_DEVICE_ID XPAR_AXI_BRAM_CTRL_2_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32U
#define XPAR_BRAM_2_ECC 0U
#define XPAR_BRAM_2_FAULT_INJECT 0U
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_2_WRITE_ACCESS 0U
#define XPAR_BRAM_2_BASEADDR 0x45200000U
#define XPAR_BRAM_2_HIGHADDR 0x45203FFFU
#define XPAR_BRAM_2_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_2_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_3 */
#define XPAR_BRAM_3_DEVICE_ID XPAR_AXI_BRAM_CTRL_3_DEVICE_ID
#define XPAR_BRAM_3_DATA_WIDTH 32U
#define XPAR_BRAM_3_ECC 0U
#define XPAR_BRAM_3_FAULT_INJECT 0U
#define XPAR_BRAM_3_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_3_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_3_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_3_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_3_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_3_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_3_WRITE_ACCESS 0U
#define XPAR_BRAM_3_BASEADDR 0x45300000U
#define XPAR_BRAM_3_HIGHADDR 0x45303FFFU
#define XPAR_BRAM_3_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_3_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_4 */
#define XPAR_BRAM_4_DEVICE_ID XPAR_AXI_BRAM_CTRL_4_DEVICE_ID
#define XPAR_BRAM_4_DATA_WIDTH 32U
#define XPAR_BRAM_4_ECC 0U
#define XPAR_BRAM_4_FAULT_INJECT 0U
#define XPAR_BRAM_4_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_4_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_4_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_4_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_4_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_4_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_4_WRITE_ACCESS 0U
#define XPAR_BRAM_4_BASEADDR 0x45400000U
#define XPAR_BRAM_4_HIGHADDR 0x45403FFFU
#define XPAR_BRAM_4_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_4_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_5 */
#define XPAR_BRAM_5_DEVICE_ID XPAR_AXI_BRAM_CTRL_5_DEVICE_ID
#define XPAR_BRAM_5_DATA_WIDTH 32U
#define XPAR_BRAM_5_ECC 0U
#define XPAR_BRAM_5_FAULT_INJECT 0U
#define XPAR_BRAM_5_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_5_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_5_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_5_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_5_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_5_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_5_WRITE_ACCESS 0U
#define XPAR_BRAM_5_BASEADDR 0x45500000U
#define XPAR_BRAM_5_HIGHADDR 0x45503FFFU
#define XPAR_BRAM_5_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_5_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_6 */
#define XPAR_BRAM_6_DEVICE_ID XPAR_AXI_BRAM_CTRL_6_DEVICE_ID
#define XPAR_BRAM_6_DATA_WIDTH 32U
#define XPAR_BRAM_6_ECC 0U
#define XPAR_BRAM_6_FAULT_INJECT 0U
#define XPAR_BRAM_6_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_6_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_6_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_6_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_6_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_6_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_6_WRITE_ACCESS 0U
#define XPAR_BRAM_6_BASEADDR 0x45600000U
#define XPAR_BRAM_6_HIGHADDR 0x45603FFFU
#define XPAR_BRAM_6_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_6_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_7 */
#define XPAR_BRAM_7_DEVICE_ID XPAR_AXI_BRAM_CTRL_7_DEVICE_ID
#define XPAR_BRAM_7_DATA_WIDTH 32U
#define XPAR_BRAM_7_ECC 0U
#define XPAR_BRAM_7_FAULT_INJECT 0U
#define XPAR_BRAM_7_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_7_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_7_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_7_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_7_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_7_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_7_WRITE_ACCESS 0U
#define XPAR_BRAM_7_BASEADDR 0x45700000U
#define XPAR_BRAM_7_HIGHADDR 0x45703FFFU
#define XPAR_BRAM_7_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_7_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x3FFFFFFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0U
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000U
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000U
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 16
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 16
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 16
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50
#define XPAR_PS7_ETHERNET_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PS7_ETHERNET_0_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 16
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 16
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 16
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/


/* Definitions for peripheral IODELAY_IF_0 */
#define XPAR_IODELAY_IF_0_BASEADDR 0x83C10000
#define XPAR_IODELAY_IF_0_HIGHADDR 0x83C1FFFF


/* Definitions for peripheral IODELAY_IF_0_DQS */
#define XPAR_IODELAY_IF_0_DQS_BASEADDR 0x83C20000
#define XPAR_IODELAY_IF_0_DQS_HIGHADDR 0x83C2FFFF


/* Definitions for peripheral IODELAY_IF_1 */
#define XPAR_IODELAY_IF_1_BASEADDR 0x83C30000
#define XPAR_IODELAY_IF_1_HIGHADDR 0x83C3FFFF


/* Definitions for peripheral IODELAY_IF_1_DQS */
#define XPAR_IODELAY_IF_1_DQS_BASEADDR 0x83C40000
#define XPAR_IODELAY_IF_1_DQS_HIGHADDR 0x83C4FFFF


/* Definitions for peripheral NVME_CTRL_0 */
#define XPAR_NVME_CTRL_0_BASEADDR 0x83C00000
#define XPAR_NVME_CTRL_0_HIGHADDR 0x83C0FFFF


/* Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFDFFFFFF


/* Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/* Definitions for peripheral T4NFC_HLPER_0 */
#define XPAR_T4NFC_HLPER_0_BASEADDR 0x43C00000
#define XPAR_T4NFC_HLPER_0_HIGHADDR 0x43C0FFFF


/* Definitions for peripheral T4NFC_HLPER_1 */
#define XPAR_T4NFC_HLPER_1_BASEADDR 0x43C10000
#define XPAR_T4NFC_HLPER_1_HIGHADDR 0x43C1FFFF


/* Definitions for peripheral T4NFC_HLPER_2 */
#define XPAR_T4NFC_HLPER_2_BASEADDR 0x43C20000
#define XPAR_T4NFC_HLPER_2_HIGHADDR 0x43C2FFFF


/* Definitions for peripheral T4NFC_HLPER_3 */
#define XPAR_T4NFC_HLPER_3_BASEADDR 0x43C30000
#define XPAR_T4NFC_HLPER_3_HIGHADDR 0x43C3FFFF


/* Definitions for peripheral T4NFC_HLPER_4 */
#define XPAR_T4NFC_HLPER_4_BASEADDR 0x43C40000
#define XPAR_T4NFC_HLPER_4_HIGHADDR 0x43C4FFFF


/* Definitions for peripheral T4NFC_HLPER_5 */
#define XPAR_T4NFC_HLPER_5_BASEADDR 0x43C50000
#define XPAR_T4NFC_HLPER_5_HIGHADDR 0x43C5FFFF


/* Definitions for peripheral T4NFC_HLPER_6 */
#define XPAR_T4NFC_HLPER_6_BASEADDR 0x43C60000
#define XPAR_T4NFC_HLPER_6_HIGHADDR 0x43C6FFFF


/* Definitions for peripheral T4NFC_HLPER_7 */
#define XPAR_T4NFC_HLPER_7_BASEADDR 0x43C70000
#define XPAR_T4NFC_HLPER_7_HIGHADDR 0x43C7FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_BASEADDR 0x81200000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x8120FFFF
#define XPAR_AXI_GPIO_0_DEVICE_ID 0
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_0_IS_DUAL 1


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_GPIO_0_BASEADDR 0x81200000
#define XPAR_GPIO_0_HIGHADDR 0x8120FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 1


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_I2C_0 */
#define XPAR_PS7_I2C_0_DEVICE_ID 0
#define XPAR_PS7_I2C_0_BASEADDR 0xE0004000
#define XPAR_PS7_I2C_0_HIGHADDR 0xE0004FFF
#define XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ 166666672


/******************************************************************/

/* Canonical definitions for peripheral PS7_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PS7_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xE0004000
#define XPAR_XIICPS_0_HIGHADDR 0xE0004FFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 166666672


/******************************************************************/

/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_PS7_QSPI_0_QSPI_MODE 2
#define XPAR_PS7_QSPI_0_QSPI_BUS_WIDTH 3


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_XQSPIPS_0_QSPI_MODE 2
#define XPAR_XQSPIPS_0_QSPI_BUS_WIDTH 3


/******************************************************************/

/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_NVME_CTRL_0_DEV_IRQ_ASSERT_INTR 61U

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0U
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100U
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FFU
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 100000000
#define XPAR_PS7_SD_0_HAS_CD 1
#define XPAR_PS7_SD_0_HAS_WP 1
#define XPAR_PS7_SD_0_BUS_WIDTH 0
#define XPAR_PS7_SD_0_MIO_BANK 0
#define XPAR_PS7_SD_0_HAS_EMIO 0


/******************************************************************/

#define XPAR_PS7_SD_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 100000000
#define XPAR_XSDPS_0_HAS_CD 1
#define XPAR_XSDPS_0_HAS_WP 1
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 0
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 0
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 100000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 100000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Xilinx FAT File System Library (XilFFs) User Settings */
#define FILE_SYSTEM_INTERFACE_SD
#define FILE_SYSTEM_USE_MKFS
#define FILE_SYSTEM_NUM_LOGIC_VOL 2
#define FILE_SYSTEM_USE_STRFUNC 0
#define FILE_SYSTEM_SET_FS_RPATH 0
#define FILE_SYSTEM_WORD_ACCESS
#endif  /* end of protection macro */
