domain_path: D:\tmp\daisyplus_micron_multi_lpddr4_a_25.1_260310\ws\daisyplus\export\daisyplus\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
