
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_0_nand_dqs_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_1_nand_dqs_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_2_nand_dqs_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_3_nand_dqs_p]
set_property ODT RTT_48 [get_ports nand_if_0_nand_dqs_p]
set_property ODT RTT_48 [get_ports nand_if_1_nand_dqs_p]
set_property ODT RTT_48 [get_ports nand_if_2_nand_dqs_p]
set_property ODT RTT_48 [get_ports nand_if_3_nand_dqs_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_0_nand_re_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_1_nand_re_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_2_nand_re_p]
set_property OUTPUT_IMPEDANCE RDRV_48_48 [get_ports nand_if_3_nand_re_p]
#set_property ODT RTT_48 [get_ports nand_if_*_nand_dqs_p]

#set_property PULLDOWN true [get_ports nand_if_0_nand_dqs_p]
set_property PULLDOWN true [get_ports nand_if_1_nand_dqs_p]
#set_property PULLDOWN true [get_ports nand_if_2_nand_dqs_p]
#set_property PULLDOWN true [get_ports nand_if_3_nand_dqs_p]
#set_property PULLUP true [get_ports nand_if_0_nand_dqs_n]
set_property PULLUP true [get_ports nand_if_1_nand_dqs_n]
#set_property PULLUP true [get_ports nand_if_2_nand_dqs_n]
#set_property PULLUP true [get_ports nand_if_3_nand_dqs_n]

set_property SLEW FAST [get_ports nand_if_*_nand_dqs_p]
set_property SLEW FAST [get_ports nand_if_*_nand_re_p]












create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/iSystemClock]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 23 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[0]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[1]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[2]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[3]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[0]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[1]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[2]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[3]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[4]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[5]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[6]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[7]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[8]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[9]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[10]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[11]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[12]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[13]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[14]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[15]} {sys_top_i/v2nfc_3/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/wea[0]} sys_top_i/v2nfc_3/inst/Inst_NPhy_Toggle_Top/wPI_BUFF_WE_PM_PHY sys_top_i/v2nfc_3/inst/Inst_NPhy_Toggle_Top/wDQOutEnable_PM_PHY]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/iSystemClock]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 76 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[0]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[1]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[2]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[3]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[0]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[1]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[2]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[3]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[4]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[5]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[6]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[7]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[8]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[9]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[10]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[11]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[12]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[13]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[14]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[15]} {sys_top_i/v2nfc_0/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/wea[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_ALE[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[0][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[1][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[2][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[3][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[4][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[5][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[6][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[7][0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CLE[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_RE_P[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_RE_P[1]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_RE_P[2]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_WE[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_WE[1]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_WE[2]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[1]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[2]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[3]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[4]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[5]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[6]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[7]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[8]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[9]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[10]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[11]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[12]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[13]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[14]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[15]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[16]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[17]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[18]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[19]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[20]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[21]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[22]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[23]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[24]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[25]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[26]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[27]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[28]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[29]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[30]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[31]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[0]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[1]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[2]} {sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[3]} sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/rDQSOut_IOBUF_T sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/wPI_BUFF_WE_PM_PHY sys_top_i/v2nfc_0/inst/Inst_NPhy_Toggle_Top/wDQOutEnable_PM_PHY]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/iSystemClock]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 76 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[0]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[1]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[2]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/rPI_ValidFlag[3]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[0]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[1]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[2]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[3]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[4]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[5]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[6]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[7]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[8]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[9]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[10]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[11]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[12]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[13]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[14]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/dina[15]} {sys_top_i/v2nfc_1/inst/Inst_NPM_Toggle_Top/Inst_NPM_Toggle_DI/PM_DI_DQ_Buffer/wea[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_ALE[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[0][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[1][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[2][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[3][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[4][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[5][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[6][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CE[7][0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_CLE[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_RE_P[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_RE_P[1]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_RE_P[2]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_WE[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_WE[1]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/O_NAND_WE[2]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[1]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[2]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[3]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[4]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[5]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[6]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[7]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[8]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[9]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[10]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[11]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[12]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[13]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[14]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[15]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[16]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[17]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[18]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[19]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[20]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[21]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[22]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[23]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[24]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[25]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[26]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[27]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[28]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[29]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[30]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/wPO_DQ_PM_PHY[31]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[0]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[1]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[2]} {sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/Inst_DQSIOBUFDS[3]} sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/Inst_NPhy_Toggle_Physical_Output/rDQSOut_IOBUF_T sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/wPI_BUFF_WE_PM_PHY sys_top_i/v2nfc_1/inst/Inst_NPhy_Toggle_Top/wDQOutEnable_PM_PHY]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ale]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_cle]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dqs_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_re_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_we]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_wp]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ale]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_cle]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dqs_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_re_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_we]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_wp]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ale]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_cle]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dqs_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_re_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_we]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_wp]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ale]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_cle]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dqs_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_re_p]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_we]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_wp]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_ce[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_0_nand_dq[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_ce[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_1_nand_dq[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_ce[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_2_nand_dq[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_ce[0]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[7]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[6]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[5]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[4]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[3]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[2]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[1]]
set_property OFFCHIP_TERM NONE [get_ports nand_if_3_nand_dq[0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_iSystemClock]
