/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	{
		"xdma_0_axibar_0_BAR0",
		"xdma_0",
		0xA0000000,
		134217728,
	},
	{
		"xdma_1_axibar_0_BAR0",
		"xdma_1",
		0xB0000000,
		134217728,
	},
	{
		"xdma_0_baseaddr_CTL0",
		"xdma_0",
		0x400000000,
		536870912,
	},
	{
		"xdma_1_baseaddr_CTL0",
		"xdma_1",
		0x500000000,
		536870912,
	},
	{
		"ddr4_0_C0_DDR4_ADDRESS_BLOCK",
		"ddr4_0",
		0x1000000000,
		34359738368,
	},
	{
		"ddr4_1_C0_DDR4_ADDRESS_BLOCK",
		"ddr4_1",
		0x2000000000,
		34359738368,
	},
	{
		"psu_ddr_0_MEM_0",
		"psu_ddr_0",
		0x00000050,
		2146434992,
	},
	/* psu_ocm_ram_0_MEM_0 memory will not be tested since application resides in the same memory */
};

int n_memory_ranges = 7;
